config/routes.rb
HomeProcessUnit::Application.routes.draw do
  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:host, :manufacture, :serial_number, :secre, :port)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :manufacture %><br>
    <%= f.text_field :manufacture %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br>
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :secre %><br>
    <%= f.text_field :secre %>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.number_field :port %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <thead>
    <tr>
      <th>Host</th>
      <th>Manufacture</th>
      <th>Serial number</th>
      <th>Secre</th>
      <th>Port</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.host %></td>
        <td><%= device.manufacture %></td>
        <td><%= device.serial_number %></td>
        <td><%= device.secre %></td>
        <td><%= device.port %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @device.host %>
</p>

<p>
  <strong>Manufacture:</strong>
  <%= @device.manufacture %>
</p>

<p>
  <strong>Serial number:</strong>
  <%= @device.serial_number %>
</p>

<p>
  <strong>Secre:</strong>
  <%= @device.secre %>
</p>

<p>
  <strong>Port:</strong>
  <%= @device.port %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeProcessUnit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>